// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OwaspTool.DAL;

#nullable disable

namespace OwaspTool.Migrations
{
    [DbContext(typeof(OwaspToolContext))]
    [Migration("20260211075656_AddWSTGTables")]
    partial class AddWSTGTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OwaspTool.Models.Database.ASVSReqAnswer", b =>
                {
                    b.Property<int>("ASVSReqAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ASVSReqAnswerID"));

                    b.Property<int>("ASVSReqLevelID")
                        .HasColumnType("int");

                    b.Property<int>("AnswerOptionID")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ASVSReqAnswerID")
                        .HasName("PK__ASVSReqA__B175C7ACC7889E67");

                    b.HasIndex("ASVSReqLevelID");

                    b.HasIndex("AnswerOptionID");

                    b.ToTable("ASVSReqAnswer");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.ASVSReqLevel", b =>
                {
                    b.Property<int>("ASVSReqLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ASVSReqLevelID"));

                    b.Property<int>("ASVSRequirementID")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LevelID")
                        .HasColumnType("int");

                    b.HasKey("ASVSReqLevelID")
                        .HasName("PK__ASVSReqL__033C98CA917DFCF9");

                    b.HasIndex("ASVSRequirementID");

                    b.HasIndex("LevelID");

                    b.ToTable("ASVSReqLevel");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.ASVSRequirement", b =>
                {
                    b.Property<int>("ASVSRequirementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ASVSRequirementID"));

                    b.Property<int>("ChapterID")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SectionID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ASVSRequirementID")
                        .HasName("PK__ASVSRequ__0E8494036DE61578");

                    b.HasIndex("ChapterID");

                    b.HasIndex("SectionID");

                    b.ToTable("ASVSRequirement");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.ASVSRequirementStatus", b =>
                {
                    b.Property<int>("ASVSRequirementStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ASVSRequirementStatusID"));

                    b.Property<int>("ASVSRequirementID")
                        .HasColumnType("int");

                    b.Property<string>("AiNotes")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserWebAppID")
                        .HasColumnType("int");

                    b.HasKey("ASVSRequirementStatusID")
                        .HasName("PK__ASVSReqS__XXXXXXXXXXXXX");

                    b.HasIndex("ASVSRequirementID");

                    b.HasIndex("UserWebAppID");

                    b.ToTable("ASVSRequirementStatus");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Answer", b =>
                {
                    b.Property<int>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerID"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nchar(255)")
                        .IsFixedLength();

                    b.HasKey("AnswerID")
                        .HasName("PK__Answer__D48250241B342D8E");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.AnswerOption", b =>
                {
                    b.Property<int>("AnswerOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerOptionID"));

                    b.Property<int>("AnswerID")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("GoToQuestionID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("AnswerOptionID")
                        .HasName("PK__AnswerOp__CEB73996917FEDCB");

                    b.HasIndex("AnswerID");

                    b.HasIndex("GoToQuestionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("AnswerOption");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SurveyID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryID")
                        .HasName("PK__Category__19093A2BA6A9D43B");

                    b.HasIndex("SurveyID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Chapter", b =>
                {
                    b.Property<int>("ChapterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterID"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ChapterID")
                        .HasName("PK__Chapter__0893A34A70945350");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.GivenAnswer", b =>
                {
                    b.Property<int>("GivenAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GivenAnswerID"));

                    b.Property<int?>("AnswerOptionID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OtherText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyInstanceID")
                        .HasColumnType("int");

                    b.HasKey("GivenAnswerID")
                        .HasName("PK__GivenAns__36DB8C0DAA3891F4");

                    b.HasIndex("AnswerOptionID");

                    b.HasIndex("SurveyInstanceID");

                    b.ToTable("GivenAnswer");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Level", b =>
                {
                    b.Property<int>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelID"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LevelID")
                        .HasName("PK__Level__09F03C063555E142");

                    b.ToTable("Level");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("InputType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionID")
                        .HasName("PK__Question__0DC06F8CE06EC61F");

                    b.HasIndex("CategoryID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Section", b =>
                {
                    b.Property<int>("SectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionID"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SectionID")
                        .HasName("PK__Section__80EF089236DD18BE");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusID")
                        .HasName("PK__Status__C8EE2043685D38B1");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Survey", b =>
                {
                    b.Property<int>("SurveyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurveyID")
                        .HasName("PK__Survey__A5481F9DEEA7B9E5");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.SurveyCategoryStatus", b =>
                {
                    b.Property<int>("SurveyCategoryStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyCategoryStatusID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSavedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("SurveyInstanceID")
                        .HasColumnType("int");

                    b.HasKey("SurveyCategoryStatusID")
                        .HasName("PK__SurveyCa__174319BD7EEF7B96");

                    b.HasIndex("CategoryID");

                    b.HasIndex("StatusID");

                    b.HasIndex("SurveyInstanceID");

                    b.ToTable("SurveyCategoryStatus");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.SurveyInstance", b =>
                {
                    b.Property<int>("SurveyInstanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyInstanceID"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SurveyID")
                        .HasColumnType("int");

                    b.Property<int>("UserWebAppID")
                        .HasColumnType("int");

                    b.HasKey("SurveyInstanceID")
                        .HasName("PK__SurveyIn__17D575E76B1E752C");

                    b.HasIndex("SurveyID");

                    b.HasIndex("UserWebAppID");

                    b.ToTable("SurveyInstance");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserID")
                        .HasName("PK__User__1788CCAC23126163");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105343DBAFF8D")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.UserWebApp", b =>
                {
                    b.Property<int>("UserWebAppID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserWebAppID"));

                    b.Property<int?>("LevelID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WebApplicationID")
                        .HasColumnType("int");

                    b.HasKey("UserWebAppID")
                        .HasName("PK__UserWebA__A55D565EAC6E88D8");

                    b.HasIndex("LevelID");

                    b.HasIndex("UserID");

                    b.HasIndex("WebApplicationID");

                    b.ToTable("UserWebApp");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WSTGChapter", b =>
                {
                    b.Property<int>("WSTGChapterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WSTGChapterID"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("WSTGChapterID")
                        .HasName("PK__WSTGChap__WSTGChapterID");

                    b.ToTable("WSTGChapter");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WSTGTest", b =>
                {
                    b.Property<int>("WSTGTestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WSTGTestID"));

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Link")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumberWSTG")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("WSTGChapterID")
                        .HasColumnType("int");

                    b.HasKey("WSTGTestID")
                        .HasName("PK__WSTGTest__WSTGTestID");

                    b.HasIndex("WSTGChapterID");

                    b.ToTable("WSTGTest");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WSTGTestAnswer", b =>
                {
                    b.Property<int>("WSTGTestAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WSTGTestAnswerID"));

                    b.Property<int>("AnswerOptionID")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("WSTGTestID")
                        .HasColumnType("int");

                    b.HasKey("WSTGTestAnswerID")
                        .HasName("PK__WSTGTest__WSTGTestAnswerID");

                    b.HasIndex("AnswerOptionID");

                    b.HasIndex("WSTGTestID");

                    b.ToTable("WSTGTestAnswer");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WSTGTestStatus", b =>
                {
                    b.Property<int>("WSTGTestStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WSTGTestStatusID"));

                    b.Property<string>("AiNotes")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserWebAppID")
                        .HasColumnType("int");

                    b.Property<int>("WSTGTestID")
                        .HasColumnType("int");

                    b.HasKey("WSTGTestStatusID")
                        .HasName("PK__WSTGTest__WSTGTestStatusID");

                    b.HasIndex("UserWebAppID");

                    b.HasIndex("WSTGTestID");

                    b.ToTable("WSTGTestStatus");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WebApplication", b =>
                {
                    b.Property<int>("WebApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebApplicationID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("WebApplicationID")
                        .HasName("PK__WebAppli__00F29777FB5ED192");

                    b.ToTable("WebApplication");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.ASVSReqAnswer", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.ASVSReqLevel", "ASVSReqLevel")
                        .WithMany("ASVSReqAnswers")
                        .HasForeignKey("ASVSReqLevelID")
                        .IsRequired()
                        .HasConstraintName("FK__ASVSReqAn__ASVSR__72C60C4A");

                    b.HasOne("OwaspTool.Models.Database.AnswerOption", "AnswerOption")
                        .WithMany("ASVSReqAnswers")
                        .HasForeignKey("AnswerOptionID")
                        .IsRequired()
                        .HasConstraintName("FK__ASVSReqAn__Answe__73BA3083");

                    b.Navigation("ASVSReqLevel");

                    b.Navigation("AnswerOption");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.ASVSReqLevel", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.ASVSRequirement", "ASVSRequirement")
                        .WithMany("ASVSReqLevels")
                        .HasForeignKey("ASVSRequirementID")
                        .IsRequired()
                        .HasConstraintName("FK__ASVSReqLe__ASVSR__6E01572D");

                    b.HasOne("OwaspTool.Models.Database.Level", "Level")
                        .WithMany("ASVSReqLevels")
                        .HasForeignKey("LevelID")
                        .IsRequired()
                        .HasConstraintName("FK__ASVSReqLe__Level__6EF57B66");

                    b.Navigation("ASVSRequirement");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.ASVSRequirement", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.Chapter", "Chapter")
                        .WithMany("ASVSRequirements")
                        .HasForeignKey("ChapterID")
                        .IsRequired()
                        .HasConstraintName("FK__ASVSRequi__Chapt__693CA210");

                    b.HasOne("OwaspTool.Models.Database.Section", "Section")
                        .WithMany("ASVSRequirements")
                        .HasForeignKey("SectionID")
                        .IsRequired()
                        .HasConstraintName("FK__ASVSRequi__Secti__6A30C649");

                    b.Navigation("Chapter");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.ASVSRequirementStatus", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.ASVSRequirement", "ASVSRequirement")
                        .WithMany()
                        .HasForeignKey("ASVSRequirementID")
                        .IsRequired()
                        .HasConstraintName("FK__ASVSReqSt__ASVSR__XXXXXX");

                    b.HasOne("OwaspTool.Models.Database.UserWebApp", "UserWebApp")
                        .WithMany()
                        .HasForeignKey("UserWebAppID")
                        .IsRequired()
                        .HasConstraintName("FK__ASVSReqSt__UserW__XXXXXX");

                    b.Navigation("ASVSRequirement");

                    b.Navigation("UserWebApp");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.AnswerOption", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.Answer", "Answer")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("AnswerID")
                        .IsRequired()
                        .HasConstraintName("FK__AnswerOpt__Answe__5535A963");

                    b.HasOne("OwaspTool.Models.Database.Question", "GoToQuestion")
                        .WithMany("AnswerOptionGoToQuestions")
                        .HasForeignKey("GoToQuestionID")
                        .HasConstraintName("FK__AnswerOpt__GoToQ__5629CD9C");

                    b.HasOne("OwaspTool.Models.Database.Question", "Question")
                        .WithMany("AnswerOptionQuestions")
                        .HasForeignKey("QuestionID")
                        .IsRequired()
                        .HasConstraintName("FK__AnswerOpt__Quest__5441852A");

                    b.Navigation("Answer");

                    b.Navigation("GoToQuestion");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Category", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.Survey", "Survey")
                        .WithMany("Categories")
                        .HasForeignKey("SurveyID")
                        .IsRequired()
                        .HasConstraintName("FK__Category__Survey__4AB81AF0");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.GivenAnswer", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.AnswerOption", "AnswerOption")
                        .WithMany("GivenAnswers")
                        .HasForeignKey("AnswerOptionID")
                        .HasConstraintName("FK__GivenAnsw__Answe__5BE2A6F2");

                    b.HasOne("OwaspTool.Models.Database.SurveyInstance", "SurveyInstance")
                        .WithMany("GivenAnswers")
                        .HasForeignKey("SurveyInstanceID")
                        .IsRequired()
                        .HasConstraintName("FK__GivenAnsw__Surve__5AEE82B9");

                    b.Navigation("AnswerOption");

                    b.Navigation("SurveyInstance");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Question", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryID")
                        .IsRequired()
                        .HasConstraintName("FK__Question__Catego__4E88ABD4");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.SurveyCategoryStatus", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.Category", "Category")
                        .WithMany("SurveyCategoryStatuses")
                        .HasForeignKey("CategoryID")
                        .IsRequired()
                        .HasConstraintName("FK__SurveyCat__Categ__619B8048");

                    b.HasOne("OwaspTool.Models.Database.Status", "Status")
                        .WithMany("SurveyCategoryStatuses")
                        .HasForeignKey("StatusID")
                        .IsRequired()
                        .HasConstraintName("FK__SurveyCat__Statu__628FA481");

                    b.HasOne("OwaspTool.Models.Database.SurveyInstance", "SurveyInstance")
                        .WithMany("SurveyCategoryStatuses")
                        .HasForeignKey("SurveyInstanceID")
                        .IsRequired()
                        .HasConstraintName("FK__SurveyCat__Surve__60A75C0F");

                    b.Navigation("Category");

                    b.Navigation("Status");

                    b.Navigation("SurveyInstance");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.SurveyInstance", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.Survey", "Survey")
                        .WithMany("SurveyInstances")
                        .HasForeignKey("SurveyID")
                        .IsRequired()
                        .HasConstraintName("FK__SurveyIns__Surve__46E78A0C");

                    b.HasOne("OwaspTool.Models.Database.UserWebApp", "UserWebApp")
                        .WithMany("SurveyInstances")
                        .HasForeignKey("UserWebAppID")
                        .IsRequired()
                        .HasConstraintName("FK__SurveyIns__UserW__45F365D3");

                    b.Navigation("Survey");

                    b.Navigation("UserWebApp");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.UserWebApp", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.Level", "Level")
                        .WithMany("UserWebApps")
                        .HasForeignKey("LevelID")
                        .HasConstraintName("FK__UserWebAp__Level__412EB0B6");

                    b.HasOne("OwaspTool.Models.Database.User", "User")
                        .WithMany("UserWebApps")
                        .HasForeignKey("UserID")
                        .IsRequired()
                        .HasConstraintName("FK__UserWebAp__UserI__3F466844");

                    b.HasOne("OwaspTool.Models.Database.WebApplication", "WebApplication")
                        .WithMany("UserWebApps")
                        .HasForeignKey("WebApplicationID")
                        .IsRequired()
                        .HasConstraintName("FK__UserWebAp__WebAp__403A8C7D");

                    b.Navigation("Level");

                    b.Navigation("User");

                    b.Navigation("WebApplication");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WSTGTest", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.WSTGChapter", "WSTGChapter")
                        .WithMany("WSTGTests")
                        .HasForeignKey("WSTGChapterID")
                        .IsRequired()
                        .HasConstraintName("FK__WSTGTest__WSTGChap__01A3B4A6");

                    b.Navigation("WSTGChapter");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WSTGTestAnswer", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.AnswerOption", "AnswerOption")
                        .WithMany()
                        .HasForeignKey("AnswerOptionID")
                        .IsRequired()
                        .HasConstraintName("FK__WSTGTestAn__Answe__03B69164");

                    b.HasOne("OwaspTool.Models.Database.WSTGTest", "WSTGTest")
                        .WithMany("WSTGTestAnswers")
                        .HasForeignKey("WSTGTestID")
                        .IsRequired()
                        .HasConstraintName("FK__WSTGTestAn__WSTGTe__02FC7413");

                    b.Navigation("AnswerOption");

                    b.Navigation("WSTGTest");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WSTGTestStatus", b =>
                {
                    b.HasOne("OwaspTool.Models.Database.UserWebApp", "UserWebApp")
                        .WithMany()
                        .HasForeignKey("UserWebAppID")
                        .IsRequired()
                        .HasConstraintName("FK__WSTGTestSt__UserW__04E4BC85");

                    b.HasOne("OwaspTool.Models.Database.WSTGTest", "WSTGTest")
                        .WithMany()
                        .HasForeignKey("WSTGTestID")
                        .IsRequired()
                        .HasConstraintName("FK__WSTGTestSt__WSTGTe__05D8E0BE");

                    b.Navigation("UserWebApp");

                    b.Navigation("WSTGTest");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.ASVSReqLevel", b =>
                {
                    b.Navigation("ASVSReqAnswers");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.ASVSRequirement", b =>
                {
                    b.Navigation("ASVSReqLevels");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Answer", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.AnswerOption", b =>
                {
                    b.Navigation("ASVSReqAnswers");

                    b.Navigation("GivenAnswers");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Category", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SurveyCategoryStatuses");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Chapter", b =>
                {
                    b.Navigation("ASVSRequirements");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Level", b =>
                {
                    b.Navigation("ASVSReqLevels");

                    b.Navigation("UserWebApps");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Question", b =>
                {
                    b.Navigation("AnswerOptionGoToQuestions");

                    b.Navigation("AnswerOptionQuestions");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Section", b =>
                {
                    b.Navigation("ASVSRequirements");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Status", b =>
                {
                    b.Navigation("SurveyCategoryStatuses");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.Survey", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("SurveyInstances");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.SurveyInstance", b =>
                {
                    b.Navigation("GivenAnswers");

                    b.Navigation("SurveyCategoryStatuses");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.User", b =>
                {
                    b.Navigation("UserWebApps");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.UserWebApp", b =>
                {
                    b.Navigation("SurveyInstances");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WSTGChapter", b =>
                {
                    b.Navigation("WSTGTests");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WSTGTest", b =>
                {
                    b.Navigation("WSTGTestAnswers");
                });

            modelBuilder.Entity("OwaspTool.Models.Database.WebApplication", b =>
                {
                    b.Navigation("UserWebApps");
                });
#pragma warning restore 612, 618
        }
    }
}
